name: pre-commit

author: liblaf

description: pre-commit

inputs:
  autofix:
    description: Auto Fix
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - run: pip install --requirement "${{ github.action_path }}/requirements.txt"
      shell: bash
      name: Install CLI
    - run: |-
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      shell: bash
      name: Setup Git
    - run: template pre-commit-ci
      shell: bash
      name: pre-commit
      env:
        AUTOFIX: ${{ inputs.autofix }}
