name: pre-commit

author: liblaf

description: pre-commit

inputs:
  autofix:
    description: git commit
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - run: pipx install "git+https://github.com/liblaf/template.git"
      shell: bash
      name: Install template
      working-directory: ${{ github.action_path }}
    - run: template pre-commit-ci
      shell: bash
      name: pre-commit
      env:
        AUTOFIX: ${{ inputs.autofix }}
        GH_TOKEN: ${{ inputs.token }}
