name: pre-commit

author: liblaf

description: pre-commit

inputs:
  autofix:
    description: git commit
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - run: pip install "git+https://github.com/liblaf/template.git"
      shell: bash
      name: Install CLI
    - run: template pre-commit-ci
      shell: bash
      name: pre-commit
      env:
        AUTOFIX: ${{ inputs.autofix }}
        GH_TOKEN: ${{ inputs.token }}
