- id: cargo-check
  name: cargo check
  entry: cargo check
  language: system
  types: [rust]
  pass_filenames: false

- id: cargo-clippy
  name: cargo clippy
  entry: cargo clippy
  language: system
  types: [rust]
  pass_filenames: false

- id: cargo-fmt
  name: cargo fmt
  entry: cargo fmt
  language: system
  types: [rust]
  pass_filenames: false

- id: shfmt
  name: shfmt
  entry: shfmt --write
  language: golang
  types: [shell]
  args: [--simplify, --indent=2, --case-indent]
  additional_dependencies:
    - mvdan.cc/sh/v3/cmd/shfmt@latest
