- id: cargo-check
  name: cargo check
  entry: cargo check
  language: system
  types:
    - rust
  pass_filenames: false
- id: cargo-clippy
  name: cargo clippy
  entry: cargo clippy
  language: system
  types:
    - rust
  pass_filenames: false
  args:
    - --fix
- id: cargo-fmt
  name: cargo fmt
  entry: cargo fmt
  language: system
  types:
    - rust
  pass_filenames: false
- id: cargo-test
  name: cargo test
  entry: cargo test
  language: system
  types:
    - rust
  pass_filenames: false
- id: prettier
  name: Prettier
  entry: prettier --write --ignore-unknown
  language: node
  types:
    - text
