name: Sync

author: liblaf

description: Sync with repository template

inputs:
  token:
    description: GitHub token
    required: false
    default: ${{ github.token }}
  commit:
    description: Commit
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - run: make --always-make --file="${{ github.action_path }}/init.mk" --ignore-errors
      shell: bash
      name: Sync with Repository Template
      env:
        GH_TOKEN: ${{ inputs.token }}
    - if: inputs.commit == 'true'
      name: Push Changes
      uses: liblaf/pre-commit-hooks/.github/actions/commit@main
      with:
        message: "ci: sync with repository template"

branding:
  color: blue
  icon: refresh-cw
