name: Sync with Template Repository

author: liblaf

description: Update current repository with template repository

inputs:
  push:
    description: Push changes to current repository
    required: false
    default: "false"
  token:
    description: GitHub token
    required: false
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - name: Install Task
      uses: arduino/setup-task@v1
    - run: task --taskfile="${{ github.action_path }}/init.yaml"
      shell: bash
      name: Sync with Template Repository
      env:
        GH_TOKEN: ${{ inputs.token }}
    - run: |-
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add --all
        if ! git diff --cached --quiet; then
          git commit --message="ci: sync with template repository"
          git push
        fi
      shell: bash
      if: inputs.push == 'true'
      name: Push Changes

branding:
  color: blue
  icon: refresh-cw
