words:
  - choco
  - gomod
  - liblaf
  - mkdocs
ignorePaths:
  - "*-lock.*"
  - "*.lock"
dictionaries:
  - bash
  - cpp
  - cpp-refined
  - dotnet
  - makefile
  - npm
  - python
allowCompoundWords: true
