name: Check

author: liblaf

description: Check CI status

inputs:
  token:
    description: GitHub token
    required: false
    default: ${{ github.token }}
  pr:
    description: PR URL
    required: false
    default: ${{ github.event.pull_request.html_url }}

runs:
  using: composite
  steps:
    - run: bash "${{ github.action_path }}/main.sh"
      shell: bash
      name: Check CI Status
      env:
        GH_TOKEN: ${{ inputs.token }}
        INPUT_PR: ${{ inputs.pr }}
