name: Install

author: liblaf

description: Install packages on various systems

inputs:
  apt:
    description: APT Packages
    required: false
    default: ""
  brew:
    description: Homebrew Packages
    required: false
    default: ""
  choco:
    description: Chocolatey Packages
    required: false
    default: ""
  other:
    description: Other Packages
    required: false
    default: ""

runs:
  using: composite
  steps:
    - run: bash "${{ github.action_path }}/scripts/apt-install.sh" ${{ inputs.apt }}
      shell: bash
      if: runner.os == 'Linux' && inputs.apt
      name: APT
    - run: bash "${{ github.action_path }}/scripts/brew-install.sh" ${{ inputs.brew }}
      shell: bash
      if: runner.os == 'macOS' && inputs.brew
      name: Homebrew
    - run: bash "${{ github.action_path }}/scripts/choco-install.sh" ${{ inputs.choco }}
      shell: bash
      if: runner.os == 'Windows' && inputs.choco
      name: Chocolatey
    - run: bash "${{ github.action_path }}/scripts/other/install.sh" ${{ inputs.other }}
      shell: bash
      if: inputs.other
      name: Other
