name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  sync:
    name: Sync All Repositories
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Sync all repositories
        run: bash scripts/sync-all.sh
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
