name: MkDocs

on:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  PYTHON_VERSION: 3.x

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip
      - name: Install Dependencies
        run: |-
          pip install \
            lxml \
            mkdocs \
            mkdocs-git-authors-plugin \
            mkdocs-git-committers-plugin-2 \
            mkdocs-git-revision-date-localized-plugin \
            mkdocs-material
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force --no-history
