name: Sync

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Sync All Repositories
        run: bash "scripts/sync-all.sh"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
