name: Test Action Install

on:
  push:

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        uses: liblaf/template/.github/actions/install@main
        with:
          brew: coreutils gnu-tar make wget
          choco: gnuwin32-coreutils.install make wget
          other: poetry task
      - run: |
          install --version
          make --version
          poetry --version
          tar --version
          task --version
          wget --version
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
