name: Test Action Install

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        uses: liblaf/template/.github/actions/install@main
        with:
          brew: coreutils gnu-tar make wget
          choco: gnuwin32-coreutils.install make wget
          other: poetry task
      - name: Check GNU coreutils
        run: install --version
      - name: Check GNU tar
        run: tar --version
      - name: Check GNU Make
        run: make --version
      - name: Check GNU Wget
        run: wget --version
      - name: Check Poetry
        run: poetry --version
      - name: Check Task
        run: task --version
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
